server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      ##validate  加载hibernate时，验证创建数据库表结构
      ##create   每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
      ##create-drop        加载hibernate时创建，退出是删除表结构
      ##update                 加载hibernate自动更新数据库结构
      ##validate 启动时验证表的结构，不会创建表
      ##none  启动时不做任何操作
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置生成的数据库是InnoDB引擎
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（毫秒）
    lettuce:
      timeout: 10000
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        #spring.redis.lettuce.pool.max-wait=-1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
      # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
      database: 0
  # 指定session的存储方式为redis
  session:
    store-type: redis



