server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ##validate  加载hibernate时，验证创建数据库表结构
      ##create   每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
      ##create-drop        加载hibernate时创建，退出是删除表结构
      ##update                 加载hibernate自动更新数据库结构
      ##validate 启动时验证表的结构，不会创建表
      ##none  启动时不做任何操作
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置生成的数据库是InnoDB引擎
